services:
  - type: web
    name: eParkKTX_BE
    env: go
    plan: free
    branch: production
    buildCommand: go build -o main ./...
    startCommand: ./main
    autoDeploy: true
    pullRequestPreviews: true
    envVars:
      - key: SQLITE_PATH
        value: eparkktx.db